# Generated by Django 4.2.7 on 2025-11-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='temp_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
