# Generated by Django 4.2.7 on 2025-11-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_is_active_emailverificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetcode',
            name='temp_token',
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='code',
            field=models.CharField(max_length=128),
        ),
    ]
