# Generated by Django 4.2.7 on 2025-11-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_passwordresetcode_temp_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='temp_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
