server {
    listen 80;

    # FRONTEND
    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }

    # BACKEND (Django)
    location /api/ {
        proxy_pass http://backend:8000;
    }

    # staticfiles do Django (opcional)
    location /static/ {
        alias /app/staticfiles/;
    }
}
