version: '3.8'

services:
  backend:
    container_name: checklist_backend
    env_file:
      - .env
    build:
      context: ./backend
    entrypoint: /app/entrypoint.sh
    command: gunicorn --config /app/gunicorn.conf.py checklist_project.wsgi:application
    restart: unless-stopped
    volumes:
      - ./backend:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    container_name: checklist_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8003:8003"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  