# Generated by Django 4.2.7 on 2025-12-01 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_registrationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationCode',
        ),
    ]
