name: Deploy Checklists Tech

on:
  push:
    branches:
      - producao

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /opt/apps/checklists.tech
            git reset --hard origin/producao
            docker compose down
            docker compose up -d --build
            docker compose ps 
